# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish Components

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore Components.sln
    - name: Build
      run: dotnet build --no-restore Components.sln --configuration Release
    - name: Publish NuGet packages
      run: |
        dotnet nuget add source --username okobets --password ${{ secrets.TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/okobets/index.json"
        dotnet nuget push "REngine/bin/Release/*.nupkg" --api-key ${{ secrets.TOKEN }} --source "github"
        dotnet nuget push "WFEngine/bin/Release/*.nupkg" --api-key ${{ secrets.TOKEN }} --source "github"
