# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: [ "main" ]
    paths:
      - "Web.Server/**"
      - "web.client/**"
      - "Web.sln"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        dotnet nuget add source --username okobets --password ${{ secrets.TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/okobets/index.json"
        dotnet restore Web.sln
    - name: Build
      run: dotnet build --no-restore Web.sln
    - name: Test .NET
      run: dotnet test --no-build --verbosity normal Web.sln
    - name: Test Angular
      run: |
        cd web.client
        npm install
        npm run test
